create query-db
kotbarmaglot/PostgreSQL-DBP pull request #1
Opened 2023-04-26 07:24 UTC by kotbarmaglot

2023-04-26 09:07 UTC, aleksandr-semenov-dbp requested changes
нужно написать запросы к БД на создание таблиц

2023-04-26 09:07 UTC, aleksandr-semenov-dbp commented on query-db.sql
> +SELECT * FROM Employees WHERE Email = '' OR Email NOT LIKE '%dualbootpartners.com';
email = '' лишнее условие, и полученный запрос не выбирает пользователей с email = NULL

2023-04-27 08:06 UTC, kotbarmaglot commented on query-db.sql
> +SELECT * FROM Employees WHERE Email = '' OR Email NOT LIKE '%dualbootpartners.com';
Запросы на создание были, просто они были уже в главной ветке. Добавил запросы и поправил условие емайл

2023-04-27 12:29 UTC, aleksandr-semenov-dbp requested changes
Таблицы Managers быть не должно, менеджеры живут вместе с остальными сотрудниками

2023-04-27 12:29 UTC, aleksandr-semenov-dbp commented on query-db.sql
> +SELECT * FROM Employees WHERE IS NULL OR Email NOT LIKE '%dualbootpartners.com';
Не похоже на валидный запрос

2023-04-28 07:58 UTC, aleksandr-semenov-dbp approved these changes

2023-04-28 11:51 UTC, merged